### ISSUE TITLE
add different icons to each title

### ISSUE THREAD

**Issue by piyush565** [msahakyan/expandable-navigation-drawer#3]
how to add drawables to each item?

**Comment by msahakyan** [comment]
Hi @piyush565,

**1.** First you have to add `ImageView` inside `layout/group_item.xml` (if you want to add icon to group item) or inside `layout/list_item.xml` (if you want to add icon to child item).

**2.** In `CustomExpandableListAdapter` we have two overridden methods:
    `getChildView` and `getGroupView` where we are inflating corresponding layouts for child and group list items. Then you should find your `ImageView` by id and set image resource you wanted to.

Example: Let's add icon to child list-item.

Change `layout/list_item.xml`

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:orientation="horizontal">

    <ImageView
        android:id="@+id/child_item_icon"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_vertical"/>

    <TextView ...
```

Change `CustomExpandableListAdapter.java`

```
    @Override
    public View getChildView(int listPosition, final int expandedListPosition,
                             boolean isLastChild, View cv, ViewGroup parent) {
        ....
        TextView expandedListTextView = (TextView) cv.findViewById(R.id.expandedListItem);
        ImageView icon = (ImageView) cv.findViewById(R.id.child_item_icon);
        icon.setImageResource(R.id.icon_resource_id);
        ....
    }
```
